//! M590Bridge daemon: demos + listen/connect text clipboard bridge + UI hub API.

use m590_daemon::hub;

use std::env;
use std::process;
use std::thread;
use std::time::{Duration, Instant};

use m590_clipboard::{
    available_backends, ClipboardService, NullClipboard, PlatformClipboard,
};
use m590_core::{
    ConnectionState, DeviceId, Message, QueueClipboardResult, Session, SessionEvent,
    APP_NAME, DEFAULT_HEARTBEAT_MISS_THRESHOLD, PROTOCOL_VERSION, VERSION,
    InboundClipboardResult,
};
use m590_net::{
    accept_framed, connect_framed, deliver, listen_on, MemoryPipe, NullTransport, TcpFrameStream,
    DEFAULT_PORT,
};

fn main() {
    if let Err(err) = run() {
        eprintln!("error: {err}");
        process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let args: Vec<String> = env::args().skip(1).collect();
    if args.is_empty() {
        return run_default_demo(false);
    }
    if args.iter().any(|a| a == "--help" || a == "-h") {
        print_help();
        return Ok(());
    }
    if args.iter().any(|a| a == "--clipboard-demo") && args[0].starts_with('-') {
        return run_default_demo(true);
    }

    match args[0].as_str() {
        "listen" => {
            let cfg = SyncCli::parse(&args[1..], SyncMode::Listen)?;
            run_listen(cfg)
        }
        "connect" => {
            let cfg = SyncCli::parse(&args[1..], SyncMode::Connect)?;
            run_connect(cfg)
        }
        "hub" => {
            let mut api = "127.0.0.1:5910".to_string();
            let mut i = 1;
            while i < args.len() {
                match args[i].as_str() {
                    "--api" => {
                        api = args
                            .get(i + 1)
                            .ok_or_else(|| "--api requires host:port".to_string())?
                            .clone();
                        i += 2;
                    }
                    "--help" | "-h" => {
                        print_help();
                        return Ok(());
                    }
                    other => return Err(format!("unknown hub argument '{other}'")),
                }
            }
            hub::run_hub(&api)
        }
        "--clipboard-demo" => run_default_demo(true),
        other if other.starts_with('-') => run_default_demo(args.iter().any(|a| a == "--clipboard-demo")),
        other => Err(format!("unknown command '{other}'. Try --help")),
    }
}

fn print_help() {
    println!(
        "{APP_NAME} daemon {VERSION}

Usage:
  m590-daemon                              # in-memory pairing demo + clipboard probe
  m590-daemon --clipboard-demo             # OS clipboard roundtrip demo
  m590-daemon listen  --code CODE [--port PORT] [options]
  m590-daemon connect --code CODE --addr HOST:PORT [options]
  m590-daemon hub [--api 127.0.0.1:5910]   # UI control API (operable shell)

Options:
  --code CODE           Pairing code (required for listen/connect)
  --port PORT           Listen port (default {DEFAULT_PORT})
  --addr HOST:PORT      Connect address (connect only)
  --device-id ID        Local device id (default autogenerated)
  --push-text TEXT      After paired, push this text once as clipboard sync
  --expect-text TEXT    Exit 0 when this text is received (test helper)
  --timeout-secs N      Max seconds (0=forever; default forever, or 30 if --push-text/--expect-text)
  --no-clipboard        Do not read/write OS clipboard (protocol-only)
  --api ADDR            hub only: control API bind (default 127.0.0.1:5910)
  --help                Show this help
"
    );
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum SyncMode {
    Listen,
    Connect,
}

#[derive(Debug)]
struct SyncCli {
    code: String,
    port: u16,
    addr: Option<String>,
    device_id: String,
    push_text: Option<String>,
    expect_text: Option<String>,
    timeout: Option<Duration>,
    use_clipboard: bool,
}

impl SyncCli {
    fn parse(args: &[String], mode: SyncMode) -> Result<Self, String> {
        let mut code = None;
        let mut port = DEFAULT_PORT;
        let mut addr = None;
        let mut device_id = None;
        let mut push_text = None;
        let mut expect_text = None;
        let mut timeout_secs: Option<u64> = None;
        let mut use_clipboard = true;

        let mut i = 0;
        while i < args.len() {
            match args[i].as_str() {
                "--code" => {
                    code = Some(require_value(args, i, "--code")?.to_string());
                    i += 2;
                }
                "--port" => {
                    port = require_value(args, i, "--port")?
                        .parse()
                        .map_err(|e| format!("invalid --port: {e}"))?;
                    i += 2;
                }
                "--addr" => {
                    addr = Some(require_value(args, i, "--addr")?.to_string());
                    i += 2;
                }
                "--device-id" => {
                    device_id = Some(require_value(args, i, "--device-id")?.to_string());
                    i += 2;
                }
                "--push-text" => {
                    push_text = Some(require_value(args, i, "--push-text")?.to_string());
                    i += 2;
                }
                "--expect-text" => {
                    expect_text = Some(require_value(args, i, "--expect-text")?.to_string());
                    i += 2;
                }
                "--timeout-secs" => {
                    timeout_secs = Some(
                        require_value(args, i, "--timeout-secs")?
                            .parse()
                            .map_err(|e| format!("invalid --timeout-secs: {e}"))?,
                    );
                    i += 2;
                }
                "--no-clipboard" => {
                    use_clipboard = false;
                    i += 1;
                }
                "--help" | "-h" => {
                    print_help();
                    process::exit(0);
                }
                other => return Err(format!("unknown argument '{other}'")),
            }
        }

        let code = code.ok_or_else(|| "--code is required".to_string())?;
        if code.is_empty() {
            return Err("pairing code must not be empty".into());
        }
        if mode == SyncMode::Connect && addr.is_none() {
            return Err("connect requires --addr HOST:PORT".into());
        }
        if mode == SyncMode::Listen && addr.is_some() {
            return Err("listen does not take --addr".into());
        }

        let device_id = device_id.unwrap_or_else(|| {
            let role = match mode {
                SyncMode::Listen => "host",
                SyncMode::Connect => "joiner",
            };
            format!("{role}-{}", process::id())
        });

        let resolved_timeout_secs = match timeout_secs {
            Some(v) => v,
            None if push_text.is_some() || expect_text.is_some() => 30,
            None => 0,
        };
        let timeout = if resolved_timeout_secs == 0 {
            None
        } else {
            Some(Duration::from_secs(resolved_timeout_secs))
        };

        let _ = mode; // validated via parse path
        Ok(Self {
            code,
            port,
            addr,
            device_id,
            push_text,
            expect_text,
            timeout,
            use_clipboard,
        })
    }
}

fn require_value<'a>(args: &'a [String], idx: usize, flag: &str) -> Result<&'a str, String> {
    args.get(idx + 1)
        .map(|s| s.as_str())
        .ok_or_else(|| format!("{flag} requires a value"))
}

fn run_listen(cfg: SyncCli) -> Result<(), String> {
    let bind = format!("0.0.0.0:{}", cfg.port);
    println!("{APP_NAME} daemon {VERSION} mode=listen");
    println!("protocol_version={PROTOCOL_VERSION}");
    println!("listen_addr={bind} code_len={} device_id={}", cfg.code.len(), cfg.device_id);

    let listener = listen_on(&bind).map_err(|e| e.to_string())?;
    let local = listener
        .local_addr()
        .map_err(|e| e.to_string())?;
    println!("listening on {local}; waiting for one peer...");

    let mut conn = accept_framed(&listener).map_err(|e| e.to_string())?;
    let peer = conn.peer_addr().map_err(|e| e.to_string())?;
    println!("peer_accepted={peer}");

    let mut session = Session::new(DeviceId::new(cfg.device_id.clone())).map_err(|e| e.to_string())?;
    // Host holds expected code; do not proactively send joiner-style outbox.
    session
        .handle(SessionEvent::StartPairing {
            expected_code: cfg.code.clone(),
        })
        .map_err(|e| e.to_string())?;
    let _ = session.take_outbox();

    run_bridge(&cfg, &mut session, &mut conn, true)
}

fn run_connect(cfg: SyncCli) -> Result<(), String> {
    let addr = cfg.addr.clone().ok_or("missing --addr")?;
    println!("{APP_NAME} daemon {VERSION} mode=connect");
    println!("protocol_version={PROTOCOL_VERSION}");
    println!("connect_addr={addr} code_len={} device_id={}", cfg.code.len(), cfg.device_id);

    let mut conn = connect_framed(&addr).map_err(|e| e.to_string())?;
    println!(
        "connected local={:?} peer={:?}",
        conn.local_addr().ok(),
        conn.peer_addr().ok()
    );

    let mut session = Session::new(DeviceId::new(cfg.device_id.clone())).map_err(|e| e.to_string())?;
    session
        .handle(SessionEvent::StartPairing {
            expected_code: cfg.code.clone(),
        })
        .map_err(|e| e.to_string())?;
    conn.send_all(session.take_outbox().iter())
        .map_err(|e| e.to_string())?;

    run_bridge(&cfg, &mut session, &mut conn, false)
}

fn run_bridge(
    cfg: &SyncCli,
    session: &mut Session,
    conn: &mut TcpFrameStream,
    is_host: bool,
) -> Result<(), String> {
    let started = Instant::now();
    let mut clipboard = open_clipboard(cfg.use_clipboard);
    let mut pushed = false;
    let mut expect_done = cfg.expect_text.is_none();
    let mut content_seq: u64 = 0;
    let role = if is_host { "host" } else { "joiner" };

    const HEARTBEAT_INTERVAL: Duration = Duration::from_secs(2);
    const PEER_IDLE_TIMEOUT: Duration = Duration::from_secs(15);

    // Pairing phase: prefer blocking reads with short timeout loops.
    while session.state() != ConnectionState::Connected {
        check_timeout(cfg, started, "pairing")?;
        match recv_with_idle(conn, Duration::from_millis(200))? {
            Some(msg) => {
                println!("{role} rx {}", msg.name());
                session
                    .handle(SessionEvent::Message(msg))
                    .map_err(|e| e.to_string())?;
                let out = session.take_outbox();
                for m in &out {
                    println!("{role} tx {}", m.name());
                }
                conn.send_all(out.iter()).map_err(|e| e.to_string())?;
            }
            None => {}
        }
    }
    println!(
        "paired=ok role={role} peer={:?}",
        session.peer_device().map(|d| d.as_str().to_string())
    );
    let mut last_peer_rx = Instant::now();
    let mut last_heartbeat = Instant::now();

    // Optional one-shot push for automated tests / manual trigger.
    if let Some(text) = &cfg.push_text {
        content_seq += 1;
        let cid = format!("push-{}-{content_seq}", process::id());
        match session
            .queue_clipboard_text(cid, text.clone())
            .map_err(|e| e.to_string())?
        {
            QueueClipboardResult::Queued => {
                let out = session.take_outbox();
                conn.send_all(out.iter()).map_err(|e| e.to_string())?;
                println!("push_text=ok len={}", text.len());
                pushed = true;
            }
            other => {
                println!("push_text=skip {other:?}");
                pushed = true;
            }
        }
        if let Some(clip) = clipboard.as_mut() {
            let _ = clip.write_text(text);
        }
    }

    if let Some(clip) = clipboard.as_mut() {
        clip.prime_poll_to_emit_current();
    }

    // Sync loop: network + heartbeat + optional OS clipboard poll.
    loop {
        check_timeout(cfg, started, "sync")?;

        // Peer idle / heartbeat-miss detection.
        if last_peer_rx.elapsed() > PEER_IDLE_TIMEOUT {
            return Err(format!(
                "peer idle timeout after {}s (no messages)",
                PEER_IDLE_TIMEOUT.as_secs()
            ));
        }
        if session.peer_heartbeat_suspect(DEFAULT_HEARTBEAT_MISS_THRESHOLD) {
            return Err(format!(
                "peer heartbeat suspect misses={}",
                session.missed_heartbeat_acks()
            ));
        }

        // Periodic heartbeat.
        if last_heartbeat.elapsed() >= HEARTBEAT_INTERVAL {
            session
                .handle(SessionEvent::HeartbeatTick)
                .map_err(|e| e.to_string())?;
            let out = session.take_outbox();
            if !out.is_empty() {
                conn.send_all(out.iter()).map_err(|e| e.to_string())?;
                println!(
                    "{role} tx heartbeat seq={:?} misses={}",
                    session.snapshot().outstanding_heartbeat_seq,
                    session.missed_heartbeat_acks()
                );
            }
            last_heartbeat = Instant::now();
        }

        // Drain available inbound frames.
        loop {
            match conn.try_recv() {
                Ok(Some(msg)) => {
                    let name = msg.name().to_string();
                    session
                        .handle(SessionEvent::Message(msg))
                        .map_err(|e| e.to_string())?;
                    last_peer_rx = Instant::now();

                    let out = session.take_outbox();
                    if !out.is_empty() {
                        for m in &out {
                            // Keep heartbeat acks quieter unless debugging.
                            if m.name() != "heartbeat_ack" {
                                println!("{role} tx {}", m.name());
                            }
                        }
                        conn.send_all(out.iter()).map_err(|e| e.to_string())?;
                    }

                    match session.take_inbound_clipboard() {
                        Some(InboundClipboardResult::Applied { content_id, text }) => {
                            println!(
                                "sync_rx content_id={content_id} len={}",
                                text.len()
                            );
                            if let Some(clip) = clipboard.as_mut() {
                                match clip.write_text(&text) {
                                    Ok(()) => println!("clipboard_write=ok"),
                                    Err(err) => println!("clipboard_write=error {err}"),
                                }
                            }
                            if let Some(expected) = &cfg.expect_text {
                                if &text == expected {
                                    println!("expect_text=ok");
                                    expect_done = true;
                                }
                            }
                        }
                        Some(InboundClipboardResult::AppliedImage {
                            content_id,
                            width,
                            height,
                            encoding,
                            data,
                        }) => {
                            println!(
                                "sync_rx_image content_id={content_id} {width}x{height} enc={encoding:?} bytes={}",
                                data.len()
                            );
                            if let Some(clip) = clipboard.as_mut() {
                                match m590_clipboard::ImageClipboard::from_wire(
                                    width, height, encoding, data,
                                ) {
                                    Ok(image) => match clip.write_image(&image) {
                                        Ok(()) => println!("clipboard_write_image=ok"),
                                        Err(err) => println!("clipboard_write_image=error {err}"),
                                    },
                                    Err(err) => println!("clipboard_write_image=error {err}"),
                                }
                            }
                        }
                        Some(InboundClipboardResult::DuplicateContentId) => {
                            println!("sync_rx=duplicate_content_id");
                        }
                        None => {
                            if name != "heartbeat" && name != "heartbeat_ack" {
                                println!("{role} rx {name}");
                            }
                        }
                    }
                }
                Ok(None) => break,
                Err(m590_net::TcpError::Disconnected) => {
                    println!("peer_disconnected=true");
                    session
                        .handle(SessionEvent::Disconnect)
                        .map_err(|e| e.to_string())?;
                    return Err("peer disconnected".into());
                }
                Err(err) => return Err(err.to_string()),
            }
        }

        // Poll local clipboard for outbound changes.
        if let Some(clip) = clipboard.as_mut() {
            // Prefer file-list (Nautilus/Explorer copy) over plain text path heuristics.
            match clip.poll_file_list_change() {
                Ok(Some(paths)) => {
                    if session.state() == ConnectionState::Connected {
                        if let Ok(Some(image)) = m590_clipboard::image_from_paths(&paths) {
                            content_seq += 1;
                            let cid = format!("clip-imgfiles-{}-{content_seq}", process::id());
                            let w = image.width;
                            let h = image.height;
                            match image.prepare_inline(m590_core::Session::INLINE_IMAGE_MAX_BYTES) {
                                Ok((encoding, data)) => {
                                    match session.queue_clipboard_image_encoded(
                                        cid, w, h, encoding, data,
                                    ) {
                                        Ok(QueueClipboardResult::Queued) => {
                                            let out = session.take_outbox();
                                            conn.send_all(out.iter()).map_err(|e| e.to_string())?;
                                            println!(
                                                "sync_tx_image_from_file_list {w}x{h} {encoding:?}"
                                            );
                                        }
                                        Ok(QueueClipboardResult::ImageTooLarge { byte_len, limit }) => {
                                            println!(
                                                "sync_tx_image=skip too_large bytes={byte_len} limit={limit}"
                                            );
                                        }
                                        Ok(_) => {}
                                        Err(err) => println!("sync_tx_image=error {err}"),
                                    }
                                }
                                Err(err) => println!("sync_tx_image=prepare_error {err}"),
                            }
                        } else if !paths.is_empty() {
                            println!("clipboard_files={paths:?} (no image decoded)");
                        }
                    }
                }
                Ok(None) => {}
                Err(err) => println!("clipboard_files_poll=error {err}"),
            }

            match clip.poll_text_change() {
                Ok(Some(text)) => {
                    if session.state() == ConnectionState::Connected {
                        content_seq += 1;
                        if let Ok(Some(image)) = m590_clipboard::image_from_clipboard_text(&text) {
                            let cid = format!("clip-imgfile-{}-{content_seq}", process::id());
                            let w = image.width;
                            let h = image.height;
                            match image.prepare_inline(m590_core::Session::INLINE_IMAGE_MAX_BYTES) {
                                Ok((encoding, data)) => {
                                    match session.queue_clipboard_image_encoded(
                                        cid, w, h, encoding, data,
                                    ) {
                                        Ok(QueueClipboardResult::Queued) => {
                                            let out = session.take_outbox();
                                            conn.send_all(out.iter()).map_err(|e| e.to_string())?;
                                            println!(
                                                "sync_tx_image_from_path {w}x{h} {encoding:?}"
                                            );
                                        }
                                        Ok(QueueClipboardResult::DuplicateContentId) => {
                                            println!("sync_tx_image=skip duplicate_content_id");
                                        }
                                        Ok(QueueClipboardResult::UnchangedImage) => {
                                            println!("clipboard_poll_image=skip_echo");
                                        }
                                        Ok(QueueClipboardResult::ImageTooLarge { byte_len, limit }) => {
                                            println!(
                                                "sync_tx_image=skip too_large bytes={byte_len} limit={limit}"
                                            );
                                        }
                                        Ok(QueueClipboardResult::UnchangedText) => {
                                            println!("sync_tx_image=skip unexpected_text_result");
                                        }
                                        Err(err) => println!("sync_tx_image=error {err}"),
                                    }
                                }
                                Err(err) => println!("sync_tx_image=prepare_error {err}"),
                            }
                        } else {
                            let cid = format!("clip-{}-{content_seq}", process::id());
                            match session.queue_clipboard_text(cid, text.clone()) {
                                Ok(QueueClipboardResult::Queued) => {
                                    let out = session.take_outbox();
                                    conn.send_all(out.iter()).map_err(|e| e.to_string())?;
                                    println!("sync_tx len={}", text.len());
                                }
                                Ok(QueueClipboardResult::DuplicateContentId) => {
                                    println!("sync_tx=skip duplicate_content_id");
                                }
                                Ok(QueueClipboardResult::UnchangedText) => {
                                    println!("clipboard_poll=skip_echo len={}", text.len());
                                }
                                Ok(QueueClipboardResult::UnchangedImage)
                                | Ok(QueueClipboardResult::ImageTooLarge { .. }) => {
                                    println!("sync_tx=skip unexpected_image_result_on_text");
                                }
                                Err(err) => println!("sync_tx=error {err}"),
                            }
                        }
                    }
                }
                Ok(None) => {}
                Err(err) => println!("clipboard_poll=error {err}"),
            }

            match clip.poll_image_change() {
                Ok(Some(image)) => {
                    if session.state() == ConnectionState::Connected {
                        content_seq += 1;
                        let cid = format!("clip-img-{}-{content_seq}", process::id());
                        match image.prepare_inline(m590_core::Session::INLINE_IMAGE_MAX_BYTES) {
                            Ok((encoding, data)) => {
                                match session.queue_clipboard_image_encoded(
                                    cid,
                                    image.width,
                                    image.height,
                                    encoding,
                                    data,
                                ) {
                                    Ok(QueueClipboardResult::Queued) => {
                                        let out = session.take_outbox();
                                        conn.send_all(out.iter()).map_err(|e| e.to_string())?;
                                        println!(
                                            "sync_tx_image {}x{} {encoding:?}",
                                            image.width, image.height
                                        );
                                    }
                                    Ok(QueueClipboardResult::DuplicateContentId) => {
                                        println!("sync_tx_image=skip duplicate_content_id");
                                    }
                                    Ok(QueueClipboardResult::UnchangedImage) => {
                                        println!("clipboard_poll_image=skip_echo");
                                    }
                                    Ok(QueueClipboardResult::ImageTooLarge { byte_len, limit }) => {
                                        println!(
                                            "sync_tx_image=skip too_large bytes={byte_len} limit={limit}"
                                        );
                                    }
                                    Ok(QueueClipboardResult::UnchangedText) => {
                                        println!("sync_tx_image=skip unexpected_text_result");
                                    }
                                    Err(err) => println!("sync_tx_image=error {err}"),
                                }
                            }
                            Err(err) => println!("sync_tx_image=prepare_error {err}"),
                        }
                    }
                }
                Ok(None) => {}
                Err(err) => println!("clipboard_poll_image=error {err}"),
            }
        }

        // Exit conditions for test helpers.
        if cfg.expect_text.is_some() && expect_done {
            println!("status=ok reason=expect_text");
            return Ok(());
        }
        if cfg.push_text.is_some() && pushed && cfg.expect_text.is_none() {
            // Give the peer a moment to read before we close the socket.
            thread::sleep(Duration::from_millis(300));
            println!("status=ok reason=push_text");
            return Ok(());
        }

        thread::sleep(Duration::from_millis(50));
    }
}

fn recv_with_idle(
    conn: &mut TcpFrameStream,
    idle: Duration,
) -> Result<Option<Message>, String> {
    conn.set_read_timeout(Some(idle)).map_err(|e| e.to_string())?;
    conn.set_nonblocking(false).map_err(|e| e.to_string())?;
    match conn.recv() {
        Ok(msg) => Ok(Some(msg)),
        Err(m590_net::TcpError::Io(err))
            if err.kind() == std::io::ErrorKind::WouldBlock
                || err.kind() == std::io::ErrorKind::TimedOut =>
        {
            Ok(None)
        }
        Err(m590_net::TcpError::Disconnected) => Err("peer disconnected during pairing".into()),
        Err(err) => Err(err.to_string()),
    }
}

fn check_timeout(cfg: &SyncCli, started: Instant, phase: &str) -> Result<(), String> {
    if let Some(timeout) = cfg.timeout {
        if started.elapsed() > timeout {
            return Err(format!("timeout after {}s during {phase}", timeout.as_secs()));
        }
    }
    Ok(())
}

fn open_clipboard(enabled: bool) -> Option<PlatformClipboard> {
    if !enabled {
        println!("clipboard=disabled");
        return None;
    }
    match PlatformClipboard::open() {
        Ok(clip) => {
            println!("clipboard_open=ok backend={:?}", clip.backend());
            Some(clip)
        }
        Err(err) => {
            println!("clipboard_open=unavailable ({err}); continuing protocol-only");
            None
        }
    }
}

fn run_default_demo(clipboard_demo: bool) -> Result<(), String> {
    let clipboard = NullClipboard::new();
    let transport = NullTransport;

    println!("{APP_NAME} daemon {VERSION}");
    println!("protocol_version={PROTOCOL_VERSION}");
    println!("status=ok");
    println!(
        "clipboard_backend={:?} available={:?}",
        clipboard.backend(),
        available_backends()
    );
    println!(
        "null_transport={:?} default_port={DEFAULT_PORT}",
        transport.connection_state()
    );

    match demo_in_memory_pairing() {
        Ok((host_state, joiner_state, content_id)) => {
            println!("demo_pairing=ok host={host_state:?} joiner={joiner_state:?}");
            println!("demo_clipboard_content_id={content_id}");
        }
        Err(err) => return Err(format!("demo_pairing failed: {err}")),
    }

    if clipboard_demo {
        match demo_platform_clipboard() {
            Ok(summary) => println!("clipboard_demo=ok {summary}"),
            Err(err) => return Err(format!("clipboard_demo failed: {err}")),
        }
    } else {
        match PlatformClipboard::detect_backend() {
            Ok(backend) => println!("clipboard_detect={backend:?}"),
            Err(err) => println!("clipboard_detect=unavailable ({err})"),
        }
        match PlatformClipboard::open() {
            Ok(mut clip) => match clip.read_text() {
                Ok(Some(text)) => {
                    println!("clipboard_open=ok backend={:?}", clip.backend());
                    println!("clipboard_text_len={}", text.len());
                }
                Ok(None) => {
                    println!(
                        "clipboard_open=ok backend={:?} text=<empty-or-non-text>",
                        clip.backend()
                    );
                }
                Err(err) => {
                    println!("clipboard_open=ok backend={:?} read_err={err}", clip.backend())
                }
            },
            Err(err) => println!("clipboard_open=unavailable ({err})"),
        }
    }
    Ok(())
}

fn demo_in_memory_pairing() -> Result<(ConnectionState, ConnectionState, String), String> {
    let mut host = Session::new(DeviceId::new("daemon-host")).map_err(|e| e.to_string())?;
    host.handle(SessionEvent::StartPairing {
        expected_code: "246810".into(),
    })
    .map_err(|e| e.to_string())?;
    let _ = host.take_outbox();

    let mut joiner = Session::new(DeviceId::new("daemon-joiner")).map_err(|e| e.to_string())?;
    joiner
        .handle(SessionEvent::StartPairing {
            expected_code: "246810".into(),
        })
        .map_err(|e| e.to_string())?;

    let mut pipe = MemoryPipe::new();
    for msg in joiner.take_outbox() {
        pipe.send_a_to_b(&msg).map_err(|e| e.to_string())?;
    }
    deliver(&mut pipe, &mut joiner, &mut host).map_err(|e| e.to_string())?;

    let queued = joiner
        .queue_clipboard_text("demo-1", "hello from daemon demo")
        .map_err(|e| e.to_string())?;
    if queued != QueueClipboardResult::Queued {
        return Err(format!("demo queue unexpected: {queued:?}"));
    }
    for msg in joiner.take_outbox() {
        pipe.send_a_to_b(&msg).map_err(|e| e.to_string())?;
    }
    deliver(&mut pipe, &mut joiner, &mut host).map_err(|e| e.to_string())?;

    let content_id = host
        .snapshot()
        .last_clipboard_content_id
        .unwrap_or_else(|| "(none)".into());

    Ok((host.state(), joiner.state(), content_id))
}

fn demo_platform_clipboard() -> Result<String, String> {
    let mut clip = PlatformClipboard::open().map_err(|e| e.to_string())?;
    let backend = clip.backend();
    let marker = format!("m590-daemon-clipboard-{}", process::id());
    clip.write_text(&marker).map_err(|e| e.to_string())?;
    let read = clip
        .read_text()
        .map_err(|e| e.to_string())?
        .ok_or_else(|| "read back empty after write".to_string())?;
    if read != marker {
        return Err(format!("roundtrip mismatch: got {read:?}"));
    }
    let mut other = PlatformClipboard::open().map_err(|e| e.to_string())?;
    let external = format!("{marker}-ext");
    other.write_text(&external).map_err(|e| e.to_string())?;
    thread::sleep(Duration::from_millis(50));
    let changed = clip.poll_text_change().map_err(|e| e.to_string())?;
    if changed.as_deref() != Some(external.as_str()) {
        return Err(format!("poll did not observe external change: {changed:?}"));
    }
    Ok(format!("backend={backend:?} roundtrip=ok poll=ok"))
}

#[cfg(test)]
mod tests {
    #[test]
    fn daemon_crate_loads() {
        assert!(!m590_core::VERSION.is_empty());
        assert_eq!(m590_core::PROTOCOL_VERSION, 1);
    }
}
